### PR TITLE
update typings for bibtex parser grammar

### LINKED ISSUE #23: schema.d.ts for astrocite-bibtex misses parameter in signature for parse
The signature for 

```
export declare function parse(input: string, options?: ParseOptions): AST;
```

changed to 

```
export function parse(input: string): CSL.Data[];
```

but the parser still supports `options`. I also get an error

```
TS2503: Cannot find namespace 'CSL'.
```

when I try to use the new signature.

### PR DESCRIPTION
**Pull request by retorquere**
Fixes #23

### CODE REVIEW

**Comment by dsifford** [comment]
Ping @hubgit

**Comment by retorquere** [comment]
This could probably be done in a cleaner way by having `grammar.d.ts` in the `src` directory, and `index.d.ts` import that, but I haven't been able to get that to work.

**Comment by dsifford** [comment]
I'm getting a feeling that you're just using the wrong `parse` function..

This library provides two of them.. One at the top level that parses to CSL.Data and another as a property of `AST` which parses to an AST.

The muscling you're doing with the patches seems like it's just you fighting against that.

(This would be easier to pinpoint if I had a code sample to see)

**Comment by retorquere** [comment]
```
import * as bibtex from 'astrocite-bibtex/lib/grammar'
```

because `grammar.d.ts` lives alongside `grammar.js`, it (incorrectly) states that `grammar.js` exports `AST.parse` (which it doesn't) and `function parse(input: string): CSL.Data[];` (which it doesn't). `index.ts` exports these, but not `grammar.js`.

**Comment by retorquere** [comment]
Technically, the proper solution would be to have the old `schema.d.ts` as `lib/grammar.d.ts` (because that does describe `grammar.js`), and a separate `index.d.ts` that would import `grammar.d.ts` and which would export `AST.parse` and `parse` (because `index.ts` does export those), but I could not get that past `npm run build`.

**Comment by dsifford** [comment]
Can you paste a small code sample showing exactly what you're attempting to do?

**Comment by dsifford** [comment]
I think I know what the problem is and it's my fault for not scrutinizing the past few PRs enough, but if my intuition is correct this should solve your problem..

Just let me see that code snippet first to confirm.

**Comment by retorquere** [comment]
```
import * as bibtex from 'astrocite-bibtex/lib/grammar'
const text = '@article{x, title={title} }'
console.log(bibtex.parse(text, { verbatimProperties: ['url'] })) // tslint:disable-line:no-console
```

gives

```
node_modules/astrocite-bibtex/lib/grammar.d.ts:172:39 - error TS2503: Cannot find namespace 'CSL'.

172 export function parse(input: string): CSL.Data[];
                                          ~~~

test.ts:3:32 - error TS2554: Expected 1 arguments, but got 2.

3 console.log(bibtex.parse(text, { verbatimProperties: ['url'] })) // tslint:disable-line:no-console
```

**Comment by dsifford** [comment]
Yep, that's what I thought..

Try pulling down #25 and instead using the following code to do what you're trying to do...

```ts
import * as bibtex from 'astrocite-bibtex'
const text = '@article{x, title={title} }'
console.log(bibtex.AST.parse(text, { verbatimProperties: ['url'] })) // tslint:disable-line:no-console
```

**Comment by retorquere** [comment]
That still gets me

```
node_modules/astrocite-bibtex/index.d.ts:172:39 - error TS2503: Cannot find namespace 'CSL'.

172 export function parse(input: string): CSL.Data[];
```

Preferably, from my pov, `grammar.js` would still come with an appropriate `grammar.d.ts`.

**Comment by dsifford** [comment]
Re: coming with an associated `grammar.d.ts` file -- I get that, but in this case it's a bit tricker because we're combining a js grammar with a ts library.

Also, it's just not common to distribute a library with a public API residing outside of the root index. There are some exceptions to this rule, but it's rare.

Let me try to see why you're getting that error still. I haven't been able to repro on my machine.

**Comment by dsifford** [comment]
Ok it should work now. Give it a try

**Comment by retorquere** [comment]
Sorry, I don't understand. What should I try now?

Is #26 more acceptable? Previously, webpack's tree-shaking was decidedly unimpressive, and I'd rather not pull in anything but the AST parser.

**Comment by retorquere** [comment]
Oh, latest from #25. I'll give that a shot, but #26 still seems cleaner to me. `grammar.d.ts` just describes `grammar.js`, and `index.d.ts` is generated automatically from `index.ts` by `tsc`.

**Comment by dsifford** [comment]
Yes, try #25 please and let me know.

**Comment by retorquere** [comment]
How would I do this? I've tried adding `"astrocite": "dsifford/astrocite#fix-bibtex-ts"` to my package.json but that doesn't install in `astrocite-bibtex`

**Comment by retorquere** [comment]
And if I do

```
npm install --save "astrocite@dsifford/astrocite#fix-bibtex-ts"
```

I get

```
Can't install github:dsifford/astrocite#10019f94849eb2adb1ef8867f320a9be056a3b38: Missing package version
```

**Comment by dsifford** [comment]
Yeah sorry, it's sort of clunky.. There might be a better way of doing this, but I've just been building the packages from this source repo and then copying and pasting the `astrocite-bibtex` directory over to the `node_modules` directory wherever you're trying to test it.

**Comment by retorquere** [comment]
OK, that seems to work, but I don't yet know whether it will tree-shake properly. I don't know how to get the current state into the other project that uses this.

**Comment by dsifford** [comment]
Try adding `”sideEffects”: false` to the package.json of the bibtex package

**Comment by retorquere** [comment]
I'll give it a shot

**Comment by dsifford** [comment]
Closing in favor of #25

**Pull request closed without merging**
